--MARCA D EAUTOS

CREATE TABLE MODELO_AUTO(
	MODELO_AUTO_ID NUMBER(2,0) 		NOT NULL,

	CLAVE VARCHAR2(4)				NOT NULL,
	DESCRIPCION VARCHAR2(30) 		NOT NULL,
	
	CONSTRAINT PK_2 PRIMARY KEY (MODELO_AUTO_ID)
	
);

CREATE TABLE MARCA_DE_AUTOS(
	MARCA_DE_AUTOS_ID NUMBER(2,0) 		NOT NULL,

	CLAVE VARCHAR2(3)					NOT NULL,
	DESCRIPCION VARCHAR2(30) 			NOT NULL,
	
	MODELO_AUTO_ID NUMBER(2,0) 			NOT NULL,
	
	CONSTRAINT PK_1 PRIMARY KEY (MARCA_DE_AUTOS_ID),
	CONSTRAINT refModelo_1 FOREIGN KEY (MODELO_AUTO_ID)
	REFERENCES MODELO_AUTO(MODELO_AUTO_ID)
);


CREATE TABLE AUTO(
	AUTO_ID NUMBER(2,0) 					NOT NULL,

	NUMERO_DE_PLACA VARCHAR2(8)				NOT NULL,
	NUMERO_DE_SERIE VARCHAR2(20) 			NOT NULL,
	YEAR NUMBER(4,0) 						NOT NULL
	
	MARCA_DE_AUTOS_ID NUMBER(2,0)			NOT NULL,
	MODELO_AUTO_ID NUMBER(2,0) 				NOT NULL,
	
	CONSTRAINT PK_3 PRIMARY KEY (AUTO_ID),
	CONSTRAINT refMarca3 FOREIGN KEY (MARCA_DE_AUTOS_ID)
	REFERENCES MARCA_DE_AUTOS(MARCA_DE_AUTOS_ID),
	CONSTRAINT refModelo_3	FOREIGN KEY (MODELO_AUTO_ID)
	REFERENCES MODELO_AUTO(MODELO_AUTO_ID)
);


CREATE TABLE ESTADO(
	ESTADO_ID NUMBER(2,0) 			NOT NULL,

	CLAVE VARCHAR2(4)				NOT NULL,
	NOMBRE VARCHAR2(20) 			NOT NULL,
	
	CONSTRAINT PK_4 PRIMARY KEY (ESTADO_ID)
	
);

CREATE TABLE DIRECCION(
	DIRECCION_ID NUMBER(2,0) 		NOT NULL,

	CODIGO_POSTAL NUMBER(5,0)		NOT NULL,
	CALLE VARCHAR2(20) 			
	NUMERO NUMBER(3,0) 			
	
	ESTADO_ID NUMBER(2,0) 			NOT NULL,
	
	CONSTRAINT PK_5 PRIMARY KEY (DIRECCION_ID),
	CONSTRAINT refEdo_5 FOREIGN KEY (ESTADO_ID)
	REFERENCES ESTADO(ESTADO_ID)	
);

CREATE TABLE TARJETA_DE_CREDITO(
	TARJETA_DE_CREDITO_ID NUMBER(2,0) 		NOT NULL,
	
	NUMERO_DE_TARJETA VARCHAR2(16) 			NOT NULL,
	NUMERO_DE_SEGURIDAD NUMBER(3,0) 		NOT NULL,
	TIPO VARCHAR2(20) 						NOT NULL,
	FECHA_DE_EXPIRACION DATE 				NOT NULL,

	CONSTRAINT PK_7 PRIMARY KEY (TARJETA_DE_CREDITO_ID)
);

CREATE TABLE CLIENTE(
	CLIENTE_ID NUMBER(2,0) 				NOT NULL,

	NOMBRE VARCHAR2(20)					NOT NULL,
	APELLIDO_PATERNO VARCHAR2(20) 		NOT NULL,
	APELLIDO_MATERNO VARCHAR2(20),		DEFAULT 'CONFIDENCIAL',
	FECHA_DE_NACIMIENTO DATE 			NOT NULL,
	RFC VARCHAR2(10),					DEFAULT 'CONFIDENCIAL',
	EMAIL VARCHAR2(30) 					NOT NULL,
	TELEFONO NUMBER(10,0) 				NOT NULL,

	DIRECCION_ID NUMBER(2,0)			NOT NULL,
	TARJETA_DE_CREDITO_ID NUMBER(2,0) 	NOT NULL,
	
	CONSTRAINT PK_6 PRIMARY KEY (CLIENTE_ID),
	CONSTRAINT refDIREC_6 FOREIGN KEY (DIRECCION_ID)
	REFERENCES DIRECCION(DIRECCION_ID),
	CONSTRAINT refCC_6	FOREIGN KEY (TARJETA_DE_CREDITO_ID)
	REFERENCES TARJETA_DE_CREDITO(TARJETA_DE_CREDITO_ID)
);

CREATE TABLE TIPO_DE_SEGURO(
	TIPO_DE_SEGURO_ID NUMBER(2,0) 	NOT NULL,
	
	CLAVE VARCHAR2(2) 			  	NOT NULL,
	DESCRIPCION VARCHAR2(20) 		NOT NULL,

	CONSTRAINT PK_9 PRIMARY KEY (TIPO_DE_SEGURO_ID)
);

CREATE TABLE COTIZACION(
	COTIZACION_ID NUMBER(2,0) 		NOT NULL,

	EDAD_CLIENTE NUMBER(3,0) 		NOT NULL,
	FECHA_DE_COTIZACION DATE 		NOT NULL,

	CLIENTE_ID NUMBER(2,0) 			NOT NULL,
	AUTO_ID NUMBER(2,0) 			NOT NULL,
	TIPO_DE_SEGURO_ID NUMBER(1,0) 	NOT NULL,

	CONSTRAINT PK_8 PRIMARY KEY (TARJETA_DE_CREDITO_ID),
	CONSTRAINT refCLIEN_8 FOREIGN KEY (CLIENTE_ID)
	REFERENCES CLIENTE(CLIENTE_ID),
	CONSTRAINT refAuto_8 FOREIGN KEY (AUTO_ID)
	REFERENCES AUTO(AUTO_ID),
	CONSTRAINT redSEG_8 FOREIGN KEY (TIPO_DE_SEGURO_ID)
	REFERENCES TIPO_DE_SEGURO(TIPO_DE_SEGURO_ID)
);

CREATE TABLE ASEGURADORAS(
	ASEGURADORA_ID NUMBER(2,0) 	NOT NULL,
	
	CLAVE VARCHAR2(3) 			NOT NULL,
	DESCRIPCION VARCHAR2(50) 	NOT NULL,

	CONSTRAINT PK_11 PRIMARY KEY (ASEGURADORA_ID)
);

CREATE TABLE AUTO_AFECTADO(
	AUTO_AFECTADO_ID NUMBER(2,0) 	NOT NULL,
	
	NUMERO_DE_SERIE VARCHAR2(20) 	NOT NULL,
	NUMERO_DE_POLIZA NUMBER(20,0)	DEFAULT 0,

	ASEGURADORA_ID NUMBER(2,0)		DEFAULT 0,
	MARCA_DE_AUTOS_ID NUMBER(2,0) 	NOT NULL,

	CONSTRAINT PK_10 PRIMARY KEY (AUTO_AFECTADO_ID),
	CONSTRAINT refASEG_10 FOREIGN KEY (ASEGURADORA_ID)
	REFERENCES ASEGURADORAS(ASEGURADORA_ID),
	CONSTRAINT redMARCA_10 FOREIGN KEY (MARCA_DE_AUTOS_ID)
	REFERENCES MARCA_DE_AUTOS(MARCA_DE_AUTOS_ID)
);

CREATE TABLE SINIESTRO_DE_COLISION(
	SINIESTRO_DE_COLISION_ID NUMBER(2,0) 	NOT NULL,
	
	NUMERO_DE_REPORTE_VIAL NUMBER(20,0) 	NOT NULL,
	GRUA CHAR(1)							DEFAULT 'N',

	AUTO_AFECTADO_ID NUMBER(2,0) 			NOT NULL,

	CONSTRAINT PK_12 PRIMARY KEY (SINIESTRO_DE_COLISION_ID),
	CONSTRAINT refAUAFECT_12 FOREIGN KEY (AUTO_AFECTADO_ID)
	REFERENCES AUTO_AFECTADO(AUTO_AFECTADO_ID)
); 


CREATE TABLE AFECTADO(
	AFECTADO_ID NUMBER(2,0) 			NOT NULL,
	
	NOMBRE VARCHAR2(20) 				NOT NULL,
	AP_PATERNO VARCHAR2(20) 			NOT NULL,
	AP_MATERNO VARCHAR2(20) 			NOT NULL,
	DAMAGE_DESCRIPTION VARCHAR2(100)	NOT NULL,
	CURP VARCHAR2(18) 					NOT NULL,

	CONSTRAINT PK_13 PRIMARY KEY (AFECTADO_ID)
);


CREATE TABLE SINIESTRO_SOCIAL(
	SINIESTRO_SOCIAL_ID NUMBER(2,0) NOT NULL,
	
	NOMBRE_HOSPITAL VARCHAR2(20)	DEFAULT 'NO APLICA',

	DIRECCION_ID NUMBER(2,0)		DEFAULT 0,
	AFECTADO_ID NUMBER(2,0) 		NOT NULL,

	CONSTRAINT PK_14 PRIMARY KEY (SINIESTRO_SOCIAL_ID),
	CONSTRAINT refDIREC_14 FOREIGN KEY (DIRECCION_ID)
	REFERENCES DIRECCION(DIRECCION_ID),
	CONSTRAINT refAFECT_14 FOREIGN KEY (AFECTADO_ID)
	REFERENCES AFECTADO(AFECTADO_ID)
);

CREATE TABLE SINIESTRO_MATERIAL(
	SINIESTRO_MATERIAL_ID NUMBER(2,0) 	NOT NULL,
	
	DESCRIPCION VARCHAR2(100) 			NOT NULL,
	URL_IMAGEN VARCHAR2(50) 			NOT NULL,

	CONSTRAINT PK_15 PRIMARY KEY (SINIESTRO_MATERIAL_ID)
);

CREATE TABLE SINIESTRO(
	SINIESTRO_ID NUMBER(2,0) 				NOT NULL,
	
	HORA_FECHA TIMESTAMP(0) 				NOT NULL,

	DIRECCION_ID NUMBER(2,0),
	SINIESTRO_DE_COLISION_ID NUMBER(2,0),
	SINIESTRO_SOCIAL_ID NUMBER(2,0),
	SINIESTRO_MATERIAL_ID NUMBER(2,0),

	CONSTRAINT PK_16 PRIMARY KEY (SINIESTRO_ID),
	CONSTRAINT refCOLI_16 FOREIGN KEY (SINIESTRO_DE_COLISION_ID)
	REFERENCES SINIESTRO_DE_COLISION(SINIESTRO_MATERIAL_ID),
	CONSTRAINT refSOCI_16 FOREIGN KEY (SINIESTRO_SOCIAL_ID)
	REFERENCES SINIESTRO_SOCIAL(SINIESTRO_SOCIAL_ID),
	CONSTRAINT refMATE_16 FOREIGN KEY (SINIESTRO_MATERIAL_ID)
	REFERENCES SINIESTRO_MATERIAL(SINIESTRO_MATERIAL_ID),
	CONSTRAINT refDIR_16 FOREIGN KEY (DIRECCION_ID)
	REFERENCES DIRECCION(DIRECCION_ID)

);

CREATE TABLE POLIZA(
	POLIZA_ID NUMBER(2,0) 				NOT NULL,
	
	FOLIO NUMBER(20,0) 					NOT NULL,
	FECHA_INICIO DATE 					NOT NULL,
	FECHA_FIN DATE 						NOT NULL,

	AUTO_ID NUMBER(2,0) 				NOT NULL,
	CLIENTE_ID NUMBER(2,0) 				NOT NULL,
	COTIZACION_ID NUMBER(2,0) 			NOT NULL,
	TARJETA_DE_CREDITO_ID NUMBER(2,0) 	NOT NULL,
	SINIESTRO_ID NUMBER(2,0) 			NOT NULL,

	CONSTRAINT PK_17 PRIMARY KEY (POLIZA_ID),
	CONSTRAINT refAUTO_17 FOREIGN KEY (AUTO_ID)
	REFERENCES AUTO(AUTO_ID),
	CONSTRAINT refCLIEN_17 FOREIGN KEY (CLIENTE_ID)
	REFERENCES CLIENTE(CLIENTE_ID),
	CONSTRAINT refCOTI_17 FOREIGN KEY (COTIZACION_ID)
	REFERENCES COTIZACION(COTIZACION_ID),
	CONSTRAINT refCC_17 FOREIGN KEY (TARJETA_DE_CREDITO_ID)
	REFERENCES TARJETA_DE_CREDITO(TARJETA_DE_CREDITO_ID),
	CONSTRAINT refSIN_17 FOREIGN KEY (SINIESTRO_ID)
	REFERENCES SINIESTRO(SINIESTRO_ID)

);